export enum QuestionType {
    FILL_IN_BLANKS = 'FILL_IN_BLANKS',
    MATCH_FOLLOWING = 'MATCH_FOLLOWING',
    DESCRIPTIVE = 'DESCRIPTIVE',
    PROGRAMMING = 'PROGRAMMING',
    IMAGE = 'IMAGE',
    AUDIO_VIDEO = 'AUDIO_VIDEO',
    ASSERTION_REASON = 'ASSERTION_REASON',
    CASE_STUDY = 'CASE_STUDY',
    NUMERICAL = 'NUMERICAL',
    DRAG_DROP = 'DRAG_DROP',
    CODE_OUTPUT = 'CODE_OUTPUT',
    SKETCH = 'SKETCH'
}
